;;; markdown-mode-file.el --- markdown-specific lisp code  -*- lexical-binding: t; -*-

;; Copyright (C) 2017  

;; Author:  <pen@firecakes>
;; Keywords: convenience,

;;;;;;;;;;Automatically generated by yf-edit-major-mode-hook;;;;;;;;;;;

(use-package markdown-toc
  :config
  (if evil-mode
      (evil-space-bind
       "ft"
       'markdown-toc-generate-or-refresh-toc)))


(provide 'markdown-mode-file)
