;;;;;;;;;;Automatically generated by yf-edit-major-mode-hook;;;;;;;;;;;

(visual-line-mode t)
(use-package evil-org
  :after org
  :config
  (evil-org-set-key-theme '(insert textobjects navigation))
  (add-hook 'org-mode-hook 'evil-org-mode)
  )

(provide 'org-mode-file)
