;;; ruby-mode-file.el --- autorun on ruby mode load  -*- lexical-binding: t; -*-

;; Copyright (C) 2017  

;; Author:  <pen@firecakes>
;; Keywords: files
;;;;;;;;;;Automatically generated by yf-edit-major-mode-hook;;;;;;;;;;;

(use-package robe
  :config
  (push 'company-robe company-backends))
(use-package rvm
  )

(provide 'ruby-mode-file)
